### ISSUE TITLE
NoMethodError: undefined method `type' for LolSoap::WSDL::NullType

### ISSUE THREAD

**Issue by akostadinov** [loco2/lolsoap#20] opened 2016-06-14 21:20 UTC
```
Exception: NoMethodError: undefined method `type' for #<LolSoap::WSDL::NullType:0x0000000545c040>
--
  0: /home/avalon/.gem/ruby/gems/lolsoap-0.8.2/lib/lolsoap/hash_builder.rb:27:in `block in children_hash'
  1: /home/avalon/.gem/ruby/gems/nokogiri-1.6.8/lib/nokogiri/xml/node_set.rb:187:in `block in each'
  2: /home/avalon/.gem/ruby/gems/nokogiri-1.6.8/lib/nokogiri/xml/node_set.rb:186:in `upto'
  3: /home/avalon/.gem/ruby/gems/nokogiri-1.6.8/lib/nokogiri/xml/node_set.rb:186:in `each'
  4: /home/avalon/.gem/ruby/gems/lolsoap-0.8.2/lib/lolsoap/hash_builder.rb:25:in `children_hash'
  5: /home/avalon/.gem/ruby/gems/lolsoap-0.8.2/lib/lolsoap/hash_builder.rb:14:in `output'
  6: /home/avalon/.gem/ruby/gems/lolsoap-0.8.2/lib/lolsoap/hash_builder.rb:27:in `block in children_hash'
  7: /home/avalon/.gem/ruby/gems/nokogiri-1.6.8/lib/nokogiri/xml/node_set.rb:187:in `block in each'
  8: /home/avalon/.gem/ruby/gems/nokogiri-1.6.8/lib/nokogiri/xml/node_set.rb:186:in `upto'
  9: /home/avalon/.gem/ruby/gems/nokogiri-1.6.8/lib/nokogiri/xml/node_set.rb:186:in `each'
 10: /home/avalon/.gem/ruby/gems/lolsoap-0.8.2/lib/lolsoap/hash_builder.rb:25:in `children_hash'
 11: /home/avalon/.gem/ruby/gems/lolsoap-0.8.2/lib/lolsoap/hash_builder.rb:14:in `output'
 12: /home/avalon/.gem/ruby/gems/lolsoap-0.8.2/lib/lolsoap/hash_builder.rb:27:in `block in children_hash'
 13: /home/avalon/.gem/ruby/gems/nokogiri-1.6.8/lib/nokogiri/xml/node_set.rb:187:in `block in each'
 14: /home/avalon/.gem/ruby/gems/nokogiri-1.6.8/lib/nokogiri/xml/node_set.rb:186:in `upto'
 15: /home/avalon/.gem/ruby/gems/nokogiri-1.6.8/lib/nokogiri/xml/node_set.rb:186:in `each'
 16: /home/avalon/.gem/ruby/gems/lolsoap-0.8.2/lib/lolsoap/hash_builder.rb:25:in `children_hash'
 17: /home/avalon/.gem/ruby/gems/lolsoap-0.8.2/lib/lolsoap/hash_builder.rb:14:in `output'
 18: /home/avalon/.gem/ruby/gems/lolsoap-0.8.2/lib/lolsoap/hash_builder.rb:27:in `block in children_hash'
 19: /home/avalon/.gem/ruby/gems/nokogiri-1.6.8/lib/nokogiri/xml/node_set.rb:187:in `block in each'
 20: /home/avalon/.gem/ruby/gems/nokogiri-1.6.8/lib/nokogiri/xml/node_set.rb:186:in `upto'
 21: /home/avalon/.gem/ruby/gems/nokogiri-1.6.8/lib/nokogiri/xml/node_set.rb:186:in `each'
 22: /home/avalon/.gem/ruby/gems/lolsoap-0.8.2/lib/lolsoap/hash_builder.rb:25:in `children_hash'
 23: /home/avalon/.gem/ruby/gems/lolsoap-0.8.2/lib/lolsoap/hash_builder.rb:14:in `output'
 24: /home/avalon/.gem/ruby/gems/lolsoap-0.8.2/lib/lolsoap/hash_builder.rb:27:in `block in children_hash'
 25: /home/avalon/.gem/ruby/gems/nokogiri-1.6.8/lib/nokogiri/xml/node_set.rb:187:in `block in each'
 26: /home/avalon/.gem/ruby/gems/nokogiri-1.6.8/lib/nokogiri/xml/node_set.rb:186:in `upto'
 27: /home/avalon/.gem/ruby/gems/nokogiri-1.6.8/lib/nokogiri/xml/node_set.rb:186:in `each'
 28: /home/avalon/.gem/ruby/gems/lolsoap-0.8.2/lib/lolsoap/hash_builder.rb:25:in `children_hash'
 29: /home/avalon/.gem/ruby/gems/lolsoap-0.8.2/lib/lolsoap/hash_builder.rb:14:in `output'
 30: /home/avalon/.gem/ruby/gems/lolsoap-0.8.2/lib/lolsoap/response.rb:38:in `body_hash'
 31: (pry):38:in `block in <top (required)>'
```
raw response:
```
<?xml version="1.0" encoding="UTF-8"?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><soapenv:Body><getWorkItemByIdResponse xmlns="http://ws.polarion.com/TrackerWebService-impl"><getWorkItemByIdReturn uri="subterra:data-service:objects:/default/OSE${WorkItem}OSE-9166" unresolvable="false" xsi:type="ns3:WorkItem" xmlns:ns1="http://ws.polarion.com/types" xmlns:ns2="http://ws.polarion.com/ProjectWebService-types" xmlns:ns3="http://ws.polarion.com/TrackerWebService-types"><ns3:approvals/><ns3:assignee/><ns3:attachments/><ns3:author uri="subterra:data-service:objects:/default/${User}user" unresolvable="false"><ns2:disabledNotifications>false</ns2:disabledNotifications><ns2:email>user@example.com</ns2:email><ns2:id>user</ns2:id><ns2:name>User Name (user)</ns2:name><ns2:voteURIs/><ns2:watcheURIs/></ns3:author><ns3:autoSuspect>false</ns3:autoSuspect><ns3:categories><ns3:Category uri="subterra:data-service:objects:/default/OSE${Category}devexp" unresolvable="false"><ns3:id>devexp</ns3:id><ns3:name>Developer Experience</ns3:name></ns3:Category></ns3:categories><ns3:comments/><ns3:created>2016-05-16T06:54:39.531Z</ns3:created><ns3:description><ns1:type>text/html</ns1:type><ns1:content>Test Tags&#xA0;</ns1:content><ns1:contentLossy>false</ns1:contentLossy></ns3:description><ns3:externallyLinkedWorkItems/><ns3:hyperlinks/><ns3:id>OSE-9166</ns3:id><ns3:linkedRevisions/><ns3:linkedRevisionsDerived/><ns3:linkedWorkItems/><ns3:linkedWorkItemsDerived/><ns3:location>default:/Products/ApplicationPlatform/OpenShift/OpenShiftEnterprise/.polarion/tracker/workitems/9000-9999/9100-9199/OSE-9166/workitem.xml</ns3:location><ns3:planningConstraints/><ns3:priority><ns3:id>50.0</ns3:id></ns3:priority><ns3:project uri="subterra:data-service:objects:/default/OSE${Project}OSE" unresolvable="false"><ns2:active>true</ns2:active><ns2:description><ns1:type>text/plain</ns1:type><ns1:content>This text comes from the project's Description in the Administration perspective. </ns1:content><ns1:contentLossy>false</ns1:contentLossy></ns2:description><ns2:id>OSE</ns2:id><ns2:lead uri="subterra:data-service:objects:/default/${User}user" unresolvable="false"><ns2:disabledNotifications>false</ns2:disabledNotifications><ns2:email>user@example.com</ns2:email><ns2:id>user</ns2:id><ns2:name>User Name (user)</ns2:name><ns2:voteURIs/><ns2:watcheURIs/></ns2:lead><ns2:location>default:/Products/ApplicationPlatform/OpenShift/OpenShiftEnterprise/.polarion/polarion-project.xml</ns2:location><ns2:name>OpenShiftEnterprise</ns2:name><ns2:projectGroupURI>subterra:data-service:objects:/default/--Products--ApplicationPlatform--OpenShift${ProjectGroup}Group</ns2:projectGroupURI><ns2:start>2015-07-20</ns2:start><ns2:trackerPrefix>OSE</ns2:trackerPrefix></ns3:project><ns3:severity><ns3:id>should_have</ns3:id></ns3:severity><ns3:status><ns3:id>draft</ns3:id></ns3:status><ns3:title>Test Tags Examples</ns3:title><ns3:type><ns3:id>testcase</ns3:id></ns3:type><ns3:updated>2016-05-16T07:23:28.183Z</ns3:updated><ns3:workRecords/><ns3:customFields><ns3:Custom><ns3:key>casecomponent</ns3:key><ns3:value xsi:type="ns3:EnumOptionId"><ns3:id xsi:type="xsd:string">auth</ns3:id></ns3:value></ns3:Custom><ns3:Custom><ns3:key>caseimportance</ns3:key><ns3:value xsi:type="ns3:EnumOptionId"><ns3:id xsi:type="xsd:string">medium</ns3:id></ns3:value></ns3:Custom><ns3:Custom><ns3:key>caselevel</ns3:key><ns3:value xsi:type="ns3:EnumOptionId"><ns3:id xsi:type="xsd:string">integration</ns3:id></ns3:value></ns3:Custom><ns3:Custom><ns3:key>caseautomation</ns3:key><ns3:value xsi:type="ns3:EnumOptionId"><ns3:id xsi:type="xsd:string">notautomated</ns3:id></ns3:value></ns3:Custom><ns3:Custom><ns3:key>caseposneg</ns3:key><ns3:value xsi:type="ns3:EnumOptionId"><ns3:id xsi:type="xsd:string">positive</ns3:id></ns3:value></ns3:Custom><ns3:Custom><ns3:key>testtype</ns3:key><ns3:value xsi:type="ns3:EnumOptionId"><ns3:id xsi:type="xsd:string">functional</ns3:id></ns3:value></ns3:Custom><ns3:Custom><ns3:key>subtype1</ns3:key><ns3:value xsi:type="ns3:EnumOptionId"><ns3:id xsi:type="xsd:string">-</ns3:id></ns3:value></ns3:Custom><ns3:Custom><ns3:key>tags</ns3:key><ns3:value xsi:type="xsd:string">ruby, mysql</ns3:value></ns3:Custom><ns3:Custom><ns3:key>products</ns3:key><ns3:value xsi:type="ns3:ArrayOfEnumOptionId"><ns3:EnumOptionId xsi:type="ns3:EnumOptionId"><ns3:id xsi:type="xsd:string">OCP, OSO</ns3:id></ns3:EnumOptionId></ns3:value></ns3:Custom></ns3:customFields></getWorkItemByIdReturn></getWorkItemByIdResponse></soapenv:Body></soapenv:Envelope>
```

WSDL is here: http://almdemo.polarion.com/polarion/ws/services/TrackerWebService?wsdl

**Comment by eugenebolshakov** [comment] 2016-06-27 11:14
I think this means that lolsoap can't handle your WSDL properly. `HashBuilder` is a simple way to convert an XML response to a hash, but it also tries to figure out if an element should be a collection (i.e. an array) based on the WSDL. If at some point it comes across a `NullType` element it means that lolsoap's WSDL parser couldn't determine the element's actual type. 

You could try to find out why that happened if you determine which element in the response causes this exception and then checking the parsed WSDL to see why it doesn't have a type. 

I'm closing this bug, but we'd welcome a PR if you can figure out why your WSDL is not supported.

**Closed by eugenebolshakov** 2016-06-27 11:14 UTC

**Comment by akostadinov** [comment] 2016-06-27 14:24
Can't understand why bug should be closed when it is indeed a bug. Regardless if you plan to fix it or not it is definitely not a closed case IMO.

With my due respect I know what OSS is and that nobody is obligated to fix my issues. But closing valid bug requests is not a receipt for success of an OSS project. Also it is fair to state in project description if you /owner(s)/ are not going to work on any bug reports. That would set right expectations so users can decide if they are ok with that or not.

I personally don't have an incentive to understand the WSDL as first I don't know WSDL in details, just want to use the freakin APIs. Also I can't control the input WSDL so even if I find the issue, that would be irrelevant. And since a simple fix in the project makes thing work, the remaining issues (be they in WSDL or lolsoap) are very low priority to me.

just my 2 cents..

**Comment by eugenebolshakov** [comment] 2016-06-28 15:13
I'm sorry, I didn't explain it very well. I didn't close this issue because it's not a bug, I closed it because it's not very helpful to keep it open as it is.

Essentially, the reason the exception is raised because lolsoap can't handle the WSDL of the API that you're trying to use. That's because lolsoap's WSDL parser is simple and only implements some parts of the WSDL spec. I.e. it's not a problem with your WSDL, it's a problem with the lolsoap's parser. 

So far we've been adding features to lolsoap's WSDL parser based on the APIs we've had to use ourselves. We'd welcome improvements to the parser, but unfortunately don't have resources to make it work with APIs we don't use ourselves. Your point about mentioning this in the project README to set the expectations right is fair, we'll look into that.

This issue would have been useful if it explained why exactly your WSDL can't be parsed properly. Neither of us are able to tell at this point, and without that it's not helpful to keep the issue open IMO (e.g. it won't help other users).

>  And since a simple fix in the project makes thing work ...

I'll comment on this in the PR, but I'd suggest not using `LolSoap::HashBuilder` and parse the response body using xpath instead as a workaround.

Hope this makes sense and I'm sorry for the frustration that this issue has caused.

**Comment by dan-higgins** [comment] 2016-12-23 23:19
This info might help make the parser more robust. When the result looks like this:
```xml
<getCustomerListResult>
  <clsCustomerInfo>...stuff...</clsCustomerInfo>
</getCustomerListResult>
```
The `LolSoap::HashBuilder` works great. However some calls I make return a result like this:
```xml
<getBookingsHistoryResult>
  <anyType xsi:type=\"clsBookingHistory\">...stuff...</anyType>
</getBookingsHistoryResult>
```
This raises the `NullType` error. I think the `<anyType>` element isn't handled the same way a direct use of `<clsBookingHistory>` would be.

Let me know if I can provide other info to solve this. Cheers.

**Comment by dan-higgins** [comment] 2016-12-23 23:55
One more info bit. The `anyType` here comes from this:
```xml
      <s:complexType name="ArrayOfAnyType">
        <s:sequence>
          <s:element minOccurs="0" maxOccurs="unbounded" name="anyType" nillable="true"/>
        </s:sequence>
      </s:complexType>
```
I can see that this might be challenging to handle in a "simple" parser.

**Comment by dan-higgins** [comment] 2016-12-24 00:02
My last bump on this closed issue... 

If I could pass a lambda to the `body_hash` method, which accepts an element/node object, and returns a possibly new element/node, then I could easily handle special cases (like the one above) and force certain elements to work. 

Just an idea.

**Comment by akostadinov** [comment] 2016-12-24 10:45
@dan-higgins , in #21 you can see a monkey patch code to get you around this issue.
